### ISSUE TITLE
Warn/abort when pthread_create() fails

### ISSUE THREAD

**Issue by keichi** [GTkorvo/evpath#16]
I had an issue where SST hangs on Fujitsu FX100 system. After some debugging, I figured pthread_create() called from cm.c was returning an error, and therefore the communication thread was not launched. (The maximum stack size of a thread needs to be manually set on FX100.) I think it would be helpful for the users to spit some error message or even abort when pthread_create() fails.

**Comment by eisenhauer** [comment]
I was looking at that code over the weekend and thinking about this.  Currently if a thread fork fails we actually do a more detailed test to see if we can fork the simplest thread and do verbose output if that fails, but that output is only visible if CMLowLevelVerbose is turned on.  It makes more sense to make this error appear regardless of verbosity settings.   Probably would have done this before, but we'd never seen it fail.  I'll push in some changes.  Once they're in, I'd appreciate you giving it a shot in an environment where it would fail and tell me if it's appropriate...

**Comment by keichi** [comment]
Thanks, I'm happy to do the test on FX100.

**Comment by keichi** [comment]
Closing this issue since the check is now implemented in SST: https://github.com/ornladios/ADIOS2/pull/972
